sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yaseenshaik790/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yaseenshaik790/docker-react npm run test
